# Generated by Django 5.0.4 on 2024-04-06 23:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alunos',
            fields=[
                ('id_aluno', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('data_nasc', models.DateField()),
                ('curso', models.CharField(max_length=255)),
                ('data_inicio', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
