# Generated by Django 5.0.4 on 2024-04-06 23:32

import alunos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alunos',
            name='cpf_aluno',
            field=models.CharField(default='', max_length=11, unique=True, validators=[alunos.models.validate_cpf]),
        ),
    ]
