# Generated by Django 5.0.4 on 2024-04-08 12:22

import alunos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0002_alunos_cpf_aluno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunos',
            name='cpf_aluno',
            field=models.CharField(max_length=11, unique=True, validators=[alunos.models.validate_cpf]),
        ),
    ]
